# Generated by Django 5.2.4 on 2025-07-06 18:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cor', models.CharField(default='#007bff', max_length=7)),
                ('icone', models.CharField(default='fas fa-calendar', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria de Evento',
                'verbose_name_plural': 'Categorias de Eventos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('show', 'Show'), ('parada', 'Parada'), ('encontro', 'Encontro com Personagens'), ('workshop', 'Workshop'), ('competicao', 'Competição'), ('especial', 'Evento Especial')], max_length=20)),
                ('faixa_etaria', models.CharField(choices=[('livre', 'Livre'), ('infantil', 'Infantil (0-12 anos)'), ('teen', 'Teen (13-17 anos)'), ('adulto', 'Adulto (18+ anos)'), ('familia', 'Família')], max_length=20)),
                ('local', models.CharField(max_length=200)),
                ('capacidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('duracao_minutos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('imagem_principal', models.URLField(blank=True)),
                ('galeria_imagens', models.TextField(blank=True, help_text='URLs das imagens separadas por vírgula')),
                ('artistas', models.TextField(blank=True, help_text='Nomes dos artistas/personagens')),
                ('requisitos', models.TextField(blank=True, help_text='Requisitos especiais')),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('gratuito', models.BooleanField(default=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avaliacao_media', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.categoriaevento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-destaque', 'data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='IngressoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gratuito', 'Gratuito'), ('pago', 'Pago'), ('vip', 'VIP'), ('premium', 'Premium')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantidade_vendida', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('esgotado', 'Esgotado'), ('suspenso', 'Suspenso')], default='disponivel', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Ingresso de Evento',
                'verbose_name_plural': 'Ingressos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Avaliação de Evento',
                'verbose_name_plural': 'Avaliações de Eventos',
                'unique_together': {('evento', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='EventoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Favorito',
                'verbose_name_plural': 'Eventos Favoritos',
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
