# Generated by Django 5.2.3 on 2025-08-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='artistas',
            field=models.TextField(blank=True, help_text='quem vai se apresentar'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='galeria_imagens',
            field=models.TextField(blank=True, help_text='URLs separadas por vírgula'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='requisitos',
            field=models.TextField(blank=True, help_text='se tem algum requisito especial'),
        ),
    ]
