# Generated by Django 5.2.4 on 2025-07-06 18:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tema', models.CharField(choices=[('adventureland', 'Adventureland'), ('fantasyland', 'Fantasyland'), ('tomorrowland', 'Tomorrowland'), ('frontierland', 'Frontierland'), ('main_street', 'Main Street')], max_length=20)),
                ('imagem', models.URLField(max_length=500)),
                ('coordenadas_mapa', models.JSONField(default=dict)),
                ('cor', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'Área do Parque',
                'verbose_name_plural': 'Áreas do Parque',
            },
        ),
        migrations.CreateModel(
            name='CategoriaAtracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('montanha_russa', 'Montanha-Russa'), ('aquatica', 'Aventura Aquática'), ('familia', 'Família'), ('radical', 'Radical'), ('infantil', 'Infantil'), ('simulador', 'Simulador'), ('show', 'Show')], max_length=20)),
                ('icone', models.CharField(default='star', max_length=50)),
                ('cor', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria de Atração',
                'verbose_name_plural': 'Categorias de Atrações',
            },
        ),
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('descricao_curta', models.CharField(max_length=300)),
                ('imagem_principal', models.URLField(max_length=500)),
                ('galeria_imagens', models.JSONField(default=list)),
                ('coordenadas_mapa', models.JSONField(default=dict)),
                ('altura_minima', models.IntegerField(blank=True, help_text='Altura mínima em cm', null=True)),
                ('altura_maxima', models.IntegerField(blank=True, help_text='Altura máxima em cm', null=True)),
                ('duracao', models.IntegerField(help_text='Duração em minutos')),
                ('capacidade', models.IntegerField(help_text='Capacidade por volta')),
                ('nivel_emocao', models.IntegerField(help_text='Nível de emoção de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ativa', models.BooleanField(default=True)),
                ('tempo_espera', models.IntegerField(default=0, help_text='Tempo de espera atual em minutos')),
                ('fast_pass_disponivel', models.BooleanField(default=False)),
                ('acessivel_cadeirante', models.BooleanField(default=False)),
                ('acesso_deficiente_auditivo', models.BooleanField(default=False)),
                ('acesso_deficiente_visual', models.BooleanField(default=False)),
                ('avaliacao', models.FloatField(default=0.0)),
                ('numero_avaliacoes', models.IntegerField(default=0)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atracoes.areaparque')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atracoes.categoriaatracao')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
            },
        ),
        migrations.CreateModel(
            name='ServicoParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('banheiro', 'Banheiro'), ('primeiros_socorros', 'Primeiros Socorros'), ('caixa_eletronico', 'Caixa Eletrônico'), ('loja_souvenir', 'Loja de Souvenirs'), ('ponto_fotografico', 'Ponto Fotográfico'), ('informacoes', 'Informações'), ('estacionamento', 'Estacionamento'), ('aluguel_carrinho', 'Aluguel de Carrinho')], max_length=20)),
                ('coordenadas_mapa', models.JSONField(default=dict)),
                ('icone', models.CharField(default='map-pin', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atracoes.areaparque')),
            ],
            options={
                'verbose_name': 'Serviço do Parque',
                'verbose_name_plural': 'Serviços do Parque',
            },
        ),
        migrations.CreateModel(
            name='TempoEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_espera', models.IntegerField(help_text='Tempo em minutos')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('atracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atracoes.atracao')),
            ],
            options={
                'verbose_name': 'Histórico de Tempo de Espera',
                'verbose_name_plural': 'Histórico de Tempos de Espera',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoAtracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atracoes.atracao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de Atração',
                'verbose_name_plural': 'Avaliações de Atrações',
                'unique_together': {('usuario', 'atracao')},
            },
        ),
        migrations.CreateModel(
            name='FavoritoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atracoes.atracao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito do Usuário',
                'verbose_name_plural': 'Favoritos dos Usuários',
                'unique_together': {('usuario', 'atracao')},
            },
        ),
    ]
