# Generated by Django 5.2.3 on 2025-08-01 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='altura_maxima',
            field=models.IntegerField(blank=True, help_text='altura máxima em cm', null=True),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='altura_minima',
            field=models.IntegerField(blank=True, help_text='altura mínima em cm', null=True),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='capacidade',
            field=models.IntegerField(help_text='quantas pessoas por vez'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='duracao',
            field=models.IntegerField(help_text='quantos minutos dura'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='nivel_emocao',
            field=models.IntegerField(help_text='de 1 (suave) a 5 (radical)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='tempo_espera',
            field=models.IntegerField(default=0, help_text='fila atual em minutos'),
        ),
    ]
