# Generated by Django 5.2.4 on 2025-07-06 18:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('codigo', models.CharField(help_text='Código promocional', max_length=50, unique=True)),
                ('tipo_desconto', models.CharField(choices=[('percentual', 'Percentual'), ('valor_fixo', 'Valor Fixo')], max_length=20)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('uso_maximo', models.IntegerField(default=1, help_text='Máximo de usos por usuário')),
                ('quantidade_maxima', models.IntegerField(blank=True, help_text='Quantidade máxima de usos total', null=True)),
                ('quantidade_usada', models.IntegerField(default=0)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo da compra', max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
            },
        ),
        migrations.CreateModel(
            name='TipoIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cor', models.CharField(default='#007bff', max_length=7)),
                ('icone', models.CharField(default='fas fa-ticket-alt', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('acesso_fast_pass', models.BooleanField(default=False)),
                ('acesso_vip', models.BooleanField(default=False)),
                ('estacionamento_gratuito', models.BooleanField(default=False)),
                ('desconto_restaurantes', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('desconto_loja', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('idade_minima', models.IntegerField(default=0)),
                ('idade_maxima', models.IntegerField(blank=True, null=True)),
                ('validade_dias', models.IntegerField(default=1, help_text='Número de dias que o ingresso é válido')),
            ],
            options={
                'verbose_name': 'Tipo de Ingresso',
                'verbose_name_plural': 'Tipos de Ingressos',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('data_uso', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('usado', 'Usado')], default='pendente', max_length=20)),
                ('valor_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_promocional', models.CharField(blank=True, max_length=50)),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('promocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingressos.promocao')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.AddField(
            model_name='promocao',
            name='tipos_aplicaveis',
            field=models.ManyToManyField(blank=True, to='ingressos.tipoingresso'),
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ingressos.compra')),
                ('tipo_ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingressos.tipoingresso')),
            ],
            options={
                'verbose_name': 'Item da Compra',
                'verbose_name_plural': 'Itens da Compra',
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('qr_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('data_validade', models.DateTimeField()),
                ('data_uso', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('usado', 'Usado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='ativo', max_length=20)),
                ('nome_visitante', models.CharField(max_length=200)),
                ('cpf_visitante', models.CharField(blank=True, max_length=14)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='ingressos.compra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to=settings.AUTH_USER_MODEL)),
                ('tipo_ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingressos.tipoingresso')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
                'ordering': ['-data_validade'],
            },
        ),
        migrations.CreateModel(
            name='UsoIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_uso', models.CharField(choices=[('entrada', 'Entrada no Parque'), ('atracao', 'Uso em Atração'), ('fast_pass', 'Fast Pass'), ('restaurante', 'Restaurante'), ('loja', 'Loja')], max_length=20)),
                ('data_uso', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='ingressos.ingresso')),
            ],
            options={
                'verbose_name': 'Uso de Ingresso',
                'verbose_name_plural': 'Usos de Ingressos',
                'ordering': ['-data_uso'],
            },
        ),
    ]
